/**
 * Edson - 21/09/2018
 */

alter table TB_TITULAR
add(
    NR_DF              	int( 3 ) null,
    NR_RDP            	int( 3 ) null,
    NR_LOCAL			int( 3 ) null,
    CD_CATEGORIA        bigint( 17 ) null,
    NM_SETOR          	varchar( 60 ) null,
    ES                  varchar( 10 ) null,
    CD_PLANO            varchar( 20 ) null,
    DT_INCLUSAO       	date null,
    TP_SEXO           	char( 1 ) null,
    PERMANENCIA         varchar( 10 ) null,
    DT_REF              date null,
    BANCO               int( 3 ),
    AGENCIA             varchar( 60 ) null,
    AGENCIA_DG          varchar( 5 ) null,
    CONTA_CORRENTE      varchar( 60 ) null,
    NR_CPF_CC         	bigint( 17 ) null,
    NM_TITULAR_CC       varchar( 200 ) null,
    CD_CARDIF     		varchar( 40 ) null,
    NR_CEP              int( 8 ),
    TP_LOGRADOURO       varchar( 40 ) null,
    NM_LOGRADOURO       varchar( 200 ) null,
    NUM_LOGRADOURO    	varchar( 10 ) null,
    COMPL               varchar( 20 ) null,
    NM_BAIRRO         	varchar( 60 ) null,
    NM_MUNICIPIO      	varchar( 80 ) null,
    UF                  char( 2 ) null,
    TEL_RESIDENCIAL     	bigint( 17 ) null,
    TEL_COMERCIAL       	bigint( 17 ) null,
    TEL_CELULAR         	bigint( 17 ) null,
    NM_MAE              	varchar( 200 ) null,
    NR_RG               	varchar( 16 ) null,
    NM_ORGAO_EMISSAO_RG    	varchar( 60 ) null,
    NM_PAIS_RG             	varchar( 80 ) null,
    DT_EMISSAO_RG       	date null,
    UF_RG               	char( 2 ) null,
    PIS                 	varchar( 80 ) null,
    CNS                 	varchar( 60 ) null,
    EMAIL               	varchar( 80 ) null,
    TP_GRAU_ESCOLARIDADE			int ( 3 ) null,
    VL_RENDA_FAMILIAR      			numeric( 17, 2 ) null,
    CD_PROFISSAO        			int( 3 ) null,
    CD_PAIS_ORIGEM      			int( 3 ) null,
    DT_EXCLUSAO             		date null,
    CD_MOTIVO_EXCLUSAO      		varchar( 60 ) null,
    CD_OPERACAO             		int( 3 ) null,
    CD_EMPRESA_TITULAR_TRANSF       int( 3 ) null,
    NR_MATRICULA_TRANSF     		bigint( 17 ) null,
    NR_LOCAL_TRANSF         		int( 3 ) null,
    CD_CATEGORIA_TRANSF     		bigint( 17 ) null,
    CD_PLANO_TRANSF         		int( 5 ) null,
    MOTIVO_REMISSAO         		varchar( 60 ) null,
    NR_CPF_NOVO_TITULAR     		bigint( 17 ) null,
    QTDE_PERM_MESES         		int( 3 ) null,
    RDP_NOVO_TITULAR        		int( 3 ) null,
    DT_INICIO_TRANSF        		date null,
    CD_STATUS               		int( 3 ) null,
    CD_ERROR                		int( 3 ) null,
    CD_DV                   		int( 3 ) null,
    BLOQ_EMPRESA_INADIMPLENCIA      varchar( 60 ) null,
    CPT                             varchar( 60 ) null,
    CD_EMPRESA_TITULAR              int( 5 ) null,
    DIF_MATRICULA_TITULAR           varchar( 60 ) null,
    NR_TITULO_ELEITOR               varchar( 80 ) null,
    NR_RIC                          varchar( 60 ) null,
    NR_CERTIDAO_NASCIMENTO          varchar( 200 ) null,
    NR_CARTEIRA_IDENT               varchar( 60 ) null,
    IND_SEGURADO_CONTRIBUTARIO      varchar( 60 ) null,
    IND_COND_EX_EMPREGADO           varchar( 60 ) null,
    IND_PERM_PLANO                  varchar( 60 ) null,
    QTDE_MESES_CONTRIB              int( 3 ) null,
    NM_BENEFICIARIO_COMPLETO        varchar( 200 ) null,
    IND_TITULAR_REMIDO              varchar( 60 ) null,
    EMAIL_SEGURADORA                varchar( 80 ) null,
    IND_PORTABILIDADE_01            varchar( 60 ) null,
    IND_PORTABILIDADE_02            varchar( 60 ) null,
    IND_CARENCIA                    varchar( 60 ) null,
    CD_PRODUTO                      int( 5 ) null,
    CD_IND_PLANO_ANTERIOR_SAS     	varchar( 60 ) null,
    CID01                           varchar( 10 ) null,
    CID02                           varchar( 10 ) null,
    CID03                           varchar( 10 ) null,
    CID04                           varchar( 10 ) null,
    CID05                           varchar( 10 ) null,
    CID06                           varchar( 10 ) null,
    CID07                           varchar( 10 ) null,
    CID08                           varchar( 10 ) null,
    CID09                           varchar( 10 ) null,
    CID10                           varchar( 10 ) null,
    IBGE                            varchar( 10 ) null,
    CBO                             varchar( 10 ) null,
    DIF_TRANSF                      varchar( 10 ) null );


alter table TB_DEPENDENTE
add(
    NR_DF              	int( 3 ) null,
    NR_RDP            	int( 3 ) null,
    NR_LOCAL			int( 3 ) null,
    CD_CATEGORIA        bigint( 17 ) null,
    NM_SETOR          	varchar( 60 ) null,
    ES                  varchar( 10 ) null,
    CD_PLANO            varchar( 20 ) null,
    DT_INCLUSAO       	date null,
    TP_SEXO           	char( 1 ) null,
    PERMANENCIA         varchar( 10 ) null,
    DT_REF              date null,
    BANCO               int( 3 ),
    AGENCIA             varchar( 60 ) null,
    AGENCIA_DG          varchar( 5 ) null,
    CONTA_CORRENTE      varchar( 60 ) null,
    NR_CPF_CC         	bigint( 17 ) null,
    NM_TITULAR_CC       varchar( 200 ) null,
    CD_CARDIF     		varchar( 40 ) null,
    NR_CEP              int( 8 ),
    TP_LOGRADOURO       varchar( 40 ) null,
    NM_LOGRADOURO       varchar( 200 ) null,
    NUM_LOGRADOURO    	varchar( 10 ) null,
    COMPL               varchar( 20 ) null,
    NM_BAIRRO         	varchar( 60 ) null,
    NM_MUNICIPIO      	varchar( 80 ) null,
    UF                  char( 2 ) null,
    TEL_RESIDENCIAL     	bigint( 17 ) null,
    TEL_COMERCIAL       	bigint( 17 ) null,
    TEL_CELULAR         	bigint( 17 ) null,
    NM_MAE              	varchar( 200 ) null,
    NR_RG               	varchar( 16 ) null,
    NM_ORGAO_EMISSAO_RG    	varchar( 60 ) null,
    NM_PAIS_RG             	varchar( 80 ) null,
    DT_EMISSAO_RG       	date null,
    UF_RG               	char( 2 ) null,
    PIS                 	varchar( 80 ) null,
    CNS                 	varchar( 60 ) null,
    EMAIL               	varchar( 80 ) null,
    TP_GRAU_ESCOLARIDADE			int ( 3 ) null,
    VL_RENDA_FAMILIAR      			numeric( 17, 2 ) null,
    CD_PROFISSAO        			int( 3 ) null,
    CD_PAIS_ORIGEM      			int( 3 ) null,
    DT_EXCLUSAO             		date null,
    CD_MOTIVO_EXCLUSAO      		varchar( 60 ) null,
    CD_OPERACAO             		int( 3 ) null,
    CD_EMPRESA_TITULAR_TRANSF       int( 3 ) null,
    NR_MATRICULA_TRANSF     		bigint( 17 ) null,
    NR_LOCAL_TRANSF         		int( 3 ) null,
    CD_CATEGORIA_TRANSF     		bigint( 17 ) null,
    CD_PLANO_TRANSF         		int( 5 ) null,
    MOTIVO_REMISSAO         		varchar( 60 ) null,
    NR_CPF_NOVO_TITULAR     		bigint( 17 ) null,
    QTDE_PERM_MESES         		int( 3 ) null,
    RDP_NOVO_TITULAR        		int( 3 ) null,
    DT_INICIO_TRANSF        		date null,
    CD_STATUS               		int( 3 ) null,
    CD_ERROR                		int( 3 ) null,
    CD_DV                   		int( 3 ) null,
    BLOQ_EMPRESA_INADIMPLENCIA      varchar( 60 ) null,
    CPT                             varchar( 60 ) null,
    CD_EMPRESA_TITULAR              int( 5 ) null,
    DIF_MATRICULA_TITULAR           varchar( 60 ) null,
    NR_TITULO_ELEITOR               varchar( 80 ) null,
    NR_RIC                          varchar( 60 ) null,
    NR_CERTIDAO_NASCIMENTO          varchar( 200 ) null,
    NR_CARTEIRA_IDENT               varchar( 60 ) null,
    IND_SEGURADO_CONTRIBUTARIO      varchar( 60 ) null,
    IND_COND_EX_EMPREGADO           varchar( 60 ) null,
    IND_PERM_PLANO                  varchar( 60 ) null,
    QTDE_MESES_CONTRIB              int( 3 ) null,
    NM_BENEFICIARIO_COMPLETO        varchar( 200 ) null,
    IND_TITULAR_REMIDO              varchar( 60 ) null,
    EMAIL_SEGURADORA                varchar( 80 ) null,
    IND_PORTABILIDADE_01            varchar( 60 ) null,
    IND_PORTABILIDADE_02            varchar( 60 ) null,
    IND_CARENCIA                    varchar( 60 ) null,
    CD_PRODUTO                      int( 5 ) null,
    CD_IND_PLANO_ANTERIOR_SAS     	varchar( 60 ) null,
    CID01                           varchar( 10 ) null,
    CID02                           varchar( 10 ) null,
    CID03                           varchar( 10 ) null,
    CID04                           varchar( 10 ) null,
    CID05                           varchar( 10 ) null,
    CID06                           varchar( 10 ) null,
    CID07                           varchar( 10 ) null,
    CID08                           varchar( 10 ) null,
    CID09                           varchar( 10 ) null,
    CID10                           varchar( 10 ) null,
    IBGE                            varchar( 10 ) null,
    CBO                             varchar( 10 ) null,
    DIF_TRANSF                      varchar( 10 ) null );

alter table TB_DESCONHECIDO
add(
    NR_DF              	int( 3 ) null,
    NR_RDP            	int( 3 ) null,
    NR_LOCAL			int( 3 ) null,
    CD_CATEGORIA        bigint( 17 ) null,
    NM_SETOR          	varchar( 60 ) null,
    ES                  varchar( 10 ) null,
    CD_PLANO            varchar( 20 ) null,
    DT_INCLUSAO       	date null,
    TP_SEXO           	char( 1 ) null,
    PERMANENCIA         varchar( 10 ) null,
    DT_REF              date null,
    BANCO               int( 3 ),
    AGENCIA             varchar( 60 ) null,
    AGENCIA_DG          varchar( 5 ) null,
    CONTA_CORRENTE      varchar( 60 ) null,
    NR_CPF_CC         	bigint( 17 ) null,
    NM_TITULAR_CC       varchar( 200 ) null,
    CD_CARDIF     		varchar( 40 ) null,
    NR_CEP              int( 8 ),
    TP_LOGRADOURO       varchar( 40 ) null,
    NM_LOGRADOURO       varchar( 200 ) null,
    NUM_LOGRADOURO    	varchar( 10 ) null,
    COMPL               varchar( 20 ) null,
    NM_BAIRRO         	varchar( 60 ) null,
    NM_MUNICIPIO      	varchar( 80 ) null,
    UF                  char( 2 ) null,
    TEL_RESIDENCIAL     	bigint( 17 ) null,
    TEL_COMERCIAL       	bigint( 17 ) null,
    TEL_CELULAR         	bigint( 17 ) null,
    NM_MAE              	varchar( 200 ) null,
    NR_RG               	varchar( 16 ) null,
    NM_ORGAO_EMISSAO_RG    	varchar( 60 ) null,
    NM_PAIS_RG             	varchar( 80 ) null,
    DT_EMISSAO_RG       	date null,
    UF_RG               	char( 2 ) null,
    PIS                 	varchar( 80 ) null,
    CNS                 	varchar( 60 ) null,
    EMAIL               	varchar( 80 ) null,
    TP_GRAU_ESCOLARIDADE			int ( 3 ) null,
    VL_RENDA_FAMILIAR      			numeric( 17, 2 ) null,
    CD_PROFISSAO        			int( 3 ) null,
    CD_PAIS_ORIGEM      			int( 3 ) null,
    DT_EXCLUSAO             		date null,
    CD_MOTIVO_EXCLUSAO      		varchar( 60 ) null,
    CD_OPERACAO             		int( 3 ) null,
    CD_EMPRESA_TITULAR_TRANSF       int( 3 ) null,
    NR_MATRICULA_TRANSF     		bigint( 17 ) null,
    NR_LOCAL_TRANSF         		int( 3 ) null,
    CD_CATEGORIA_TRANSF     		bigint( 17 ) null,
    CD_PLANO_TRANSF         		int( 5 ) null,
    MOTIVO_REMISSAO         		varchar( 60 ) null,
    NR_CPF_NOVO_TITULAR     		bigint( 17 ) null,
    QTDE_PERM_MESES         		int( 3 ) null,
    RDP_NOVO_TITULAR        		int( 3 ) null,
    DT_INICIO_TRANSF        		date null,
    CD_STATUS               		int( 3 ) null,
    CD_ERROR                		int( 3 ) null,
    CD_DV                   		int( 3 ) null,
    BLOQ_EMPRESA_INADIMPLENCIA      varchar( 60 ) null,
    CPT                             varchar( 60 ) null,
    CD_EMPRESA_TITULAR              int( 5 ) null,
    DIF_MATRICULA_TITULAR           varchar( 60 ) null,
    NR_TITULO_ELEITOR               varchar( 80 ) null,
    NR_RIC                          varchar( 60 ) null,
    NR_CERTIDAO_NASCIMENTO          varchar( 200 ) null,
    NR_CARTEIRA_IDENT               varchar( 60 ) null,
    IND_SEGURADO_CONTRIBUTARIO      varchar( 60 ) null,
    IND_COND_EX_EMPREGADO           varchar( 60 ) null,
    IND_PERM_PLANO                  varchar( 60 ) null,
    QTDE_MESES_CONTRIB              int( 3 ) null,
    NM_BENEFICIARIO_COMPLETO        varchar( 200 ) null,
    IND_TITULAR_REMIDO              varchar( 60 ) null,
    EMAIL_SEGURADORA                varchar( 80 ) null,
    IND_PORTABILIDADE_01            varchar( 60 ) null,
    IND_PORTABILIDADE_02            varchar( 60 ) null,
    IND_CARENCIA                    varchar( 60 ) null,
    CD_PRODUTO                      int( 5 ) null,
    CD_IND_PLANO_ANTERIOR_SAS     	varchar( 60 ) null,
    CID01                           varchar( 10 ) null,
    CID02                           varchar( 10 ) null,
    CID03                           varchar( 10 ) null,
    CID04                           varchar( 10 ) null,
    CID05                           varchar( 10 ) null,
    CID06                           varchar( 10 ) null,
    CID07                           varchar( 10 ) null,
    CID08                           varchar( 10 ) null,
    CID09                           varchar( 10 ) null,
    CID10                           varchar( 10 ) null,
    IBGE                            varchar( 10 ) null,
    CBO                             varchar( 10 ) null,
    DIF_TRANSF                      varchar( 10 ) null );    